/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/loicalleyne/bufarrowlib/cbinding */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "exports.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 5 "pool_exports.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int BufarrowNewFromFile(char* protoPath, char* msgName, char** importPaths, int nPaths, char* optsJSON, void** outHandle);
extern int BufarrowNewFromConfig(char* configPath, void** outHandle);
extern int BufarrowNewFromConfigString(char* configYAML, int configLen, void** outHandle);
extern int BufarrowClone(void* handle, void** outHandle);
extern void BufarrowFree(void* handle);
extern int BufarrowAppendRaw(void* handle, void* data, int dataLen);
extern int BufarrowAppendDenormRaw(void* handle, void* data, int dataLen);
extern int BufarrowAppendRawMerged(void* handle, void* baseData, int baseLen, void* customData, int customLen);
extern int BufarrowAppendDenormRawMerged(void* handle, void* baseData, int baseLen, void* customData, int customLen);
extern int BufarrowFlush(void* handle, void* outArray, void* outSchema);
extern int BufarrowFlushDenorm(void* handle, void* outArray, void* outSchema);
extern int BufarrowGetSchema(void* handle, void* outSchema);
extern int BufarrowGetDenormSchema(void* handle, void* outSchema);
extern int BufarrowWriteParquet(void* handle, char* filePath);
extern int BufarrowWriteParquetDenorm(void* handle, char* filePath);
extern int BufarrowReadParquet(void* handle, char* filePath, char* columnsJSON, void* outArray, void* outSchema);
extern char* BufarrowFieldNames(void* handle);
extern char* BufarrowLastError(void* handle);
extern void BufarrowFreeString(char* s);
extern char* BufarrowVersion(void);
extern char* BufarrowGetGlobalError(void);
extern int BufarrowNewHyperType(char* protoPath, char* msgName, char** importPaths, int nPaths, int64_t threshold, double rate, void** outHandle);
extern void BufarrowFreeHyperType(void* handle);
extern int BufarrowNewFromFileWithHyperType(char* protoPath, char* msgName, char** importPaths, int nPaths, char* optsJSON, void* hyperHandle, void** outHandle);
extern int BufarrowPoolNew(char* protoPath, char* msgName, char** importPaths, int nPaths, char* optsJSON, int workers, int capacity, void** outHandle);
extern int BufarrowPoolNewWithHyperType(char* protoPath, char* msgName, char** importPaths, int nPaths, char* optsJSON, void* hyperHandle, int workers, int capacity, void** outHandle);
extern int BufarrowPoolSubmit(void* handle, void* data, int dataLen);
extern int BufarrowPoolSubmitMerged(void* handle, void* baseData, int baseLen, void* customData, int customLen);
extern int BufarrowPoolFlush(void* handle, void* outArray, void* outSchema);
extern int BufarrowPoolPending(void* handle);
extern char* BufarrowPoolLastError(void* handle);
extern void BufarrowPoolFree(void* handle);

#ifdef __cplusplus
}
#endif
